extends Node

#events
@warning_ignore("unused_signal")
signal event_triggered(event : EventContext) 
@warning_ignore("unused_signal")
signal on_item_picked_up(item)
@warning_ignore("unused_signal")
signal on_upgrade_picked_up(item)
@warning_ignore("unused_signal")
signal on_upgrade_removed(item)
@warning_ignore("unused_signal")
signal on_pickup(item)
@warning_ignore("unused_signal")
signal equip_item(slot)
@warning_ignore("unused_signal")
signal use_equipped_item(slot)
@warning_ignore("unused_signal")
signal item_used(item)
@warning_ignore("unused_signal")
signal status_applied(status)
@warning_ignore("unused_signal")
signal effects_applied(target, ItemEffects)
@warning_ignore("unused_signal")
signal effects_removed(target, ItemEffects)

#REMOVE 
@warning_ignore("unused_signal")
signal action_timer_begin(action_time)
@warning_ignore("unused_signal")
signal action_timer_end(cooldown_time)
@warning_ignore("unused_signal")
signal action_timer_complete()
